### ISSUE TITLE
Overall view of Part 1

### ISSUE THREAD

**Issue by marisarabia** [unbalancedparentheses/data_science_in_julia_for_hackers#193]
# Part 1

- [ ] Current Prologue (suggested Introduction in previous issue, # 190) can be merged with current Chapter 1 since it keeps clarifying Authors’ point of view for a better reading and understanding of the book. It has been written in a similar tone. 

- [ ] Add a definition of Data Science there, it is missing at the beginning. 

- [ ] When actual Prologue and Chapter 1 are merged into the Introduction, Part I could be renamed as “Get familiar with Julia and programming”. And current Chapter 2, splitted in 3: #NewCh1 “Meeting Julia”, #NewCh2 “Using Julia” and #NewCh3 “Julia for data science”.
